// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	cache "github.com/johnfercher/maroto/v2/internal/cache"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	gofpdf "github.com/johnfercher/maroto/v2/internal/providers/gofpdf"

	mock "github.com/stretchr/testify/mock"
)

// Builder is an autogenerated mock type for the Builder type
type Builder struct {
	mock.Mock
}

type Builder_Expecter struct {
	mock *mock.Mock
}

func (_m *Builder) EXPECT() *Builder_Expecter { _ = "STUB: not implemented"; return nil }

// Build provides a mock function with given fields: cfg, _a1
func (_m *Builder) Build(cfg *entity.Config, _a1 cache.Cache) *gofpdf.Dependencies {
	_ = "STUB: not implemented"
	return nil
}

// Builder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type Builder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - cfg *entity.Config
//   - _a1 cache.Cache
func (_e *Builder_Expecter) Build(cfg interface{}, _a1 interface{}) *Builder_Build_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Builder_Build_Call) Run(run func(cfg *entity.Config, _a1 cache.Cache)) *Builder_Build_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Builder_Build_Call) Return(_a0 *gofpdf.Dependencies) *Builder_Build_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Builder_Build_Call) RunAndReturn(run func(*entity.Config, cache.Cache) *gofpdf.Dependencies) *Builder_Build_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewBuilder creates a new instance of Builder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilder(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Builder {
	_ = "STUB: not implemented"
	return nil
}
