// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	extension "github.com/johnfercher/maroto/v2/pkg/consts/extension"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter { _ = "STUB: not implemented"; return nil }

// AddImage provides a mock function with given fields: value, image
func (_m *Cache) AddImage(value string, image *entity.Image) { _ = "STUB: not implemented"; return }

// Cache_AddImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddImage'
type Cache_AddImage_Call struct {
	*mock.Call
}

// AddImage is a helper method to define mock.On call
//   - value string
//   - image *entity.Image
func (_e *Cache_Expecter) AddImage(value interface{}, image interface{}) *Cache_AddImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Cache_AddImage_Call) Run(run func(value string, image *entity.Image)) *Cache_AddImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Cache_AddImage_Call) Return() *Cache_AddImage_Call { _ = "STUB: not implemented"; return nil }

func (_c *Cache_AddImage_Call) RunAndReturn(run func(string, *entity.Image)) *Cache_AddImage_Call {
	_ = "STUB: not implemented"
	return nil

	// GetImage provides a mock function with given fields: value, _a1
}

func (_m *Cache) GetImage(value string, _a1 extension.Type) (*entity.Image, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Cache_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type Cache_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - value string
//   - _a1 extension.Type
func (_e *Cache_Expecter) GetImage(value interface{}, _a1 interface{}) *Cache_GetImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Cache_GetImage_Call) Run(run func(value string, _a1 extension.Type)) *Cache_GetImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Cache_GetImage_Call) Return(_a0 *entity.Image, _a1 error) *Cache_GetImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Cache_GetImage_Call) RunAndReturn(run func(string, extension.Type) (*entity.Image, error)) *Cache_GetImage_Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadImage provides a mock function with given fields: value, _a1
func (_m *Cache) LoadImage(value string, _a1 extension.Type) error {
	_ = "STUB: not implemented"
	return nil
}

// Cache_LoadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadImage'
type Cache_LoadImage_Call struct {
	*mock.Call
}

// LoadImage is a helper method to define mock.On call
//   - value string
//   - _a1 extension.Type
func (_e *Cache_Expecter) LoadImage(value interface{}, _a1 interface{}) *Cache_LoadImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Cache_LoadImage_Call) Run(run func(value string, _a1 extension.Type)) *Cache_LoadImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Cache_LoadImage_Call) Return(_a0 error) *Cache_LoadImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Cache_LoadImage_Call) RunAndReturn(run func(string, extension.Type) error) *Cache_LoadImage_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Cache {
	_ = "STUB: not implemented"
	return nil
}
