// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	cellwriter "github.com/johnfercher/maroto/v2/internal/providers/gofpdf/cellwriter"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// CellWriter is an autogenerated mock type for the CellWriter type
type CellWriter struct {
	mock.Mock
}

type CellWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *CellWriter) EXPECT() *CellWriter_Expecter { _ = "STUB: not implemented"; return nil }

// Apply provides a mock function with given fields: width, height, config, prop
func (_m *CellWriter) Apply(width float64, height float64, config *entity.Config, prop *props.Cell) {
	_ = "STUB: not implemented"
	return
}

// CellWriter_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type CellWriter_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - width float64
//   - height float64
//   - config *entity.Config
//   - prop *props.Cell
func (_e *CellWriter_Expecter) Apply(width interface{}, height interface{}, config interface{}, prop interface{}) *CellWriter_Apply_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_Apply_Call) Run(run func(width float64, height float64, config *entity.Config, prop *props.Cell)) *CellWriter_Apply_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_Apply_Call) Return() *CellWriter_Apply_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_Apply_Call) RunAndReturn(run func(float64, float64, *entity.Config, *props.Cell)) *CellWriter_Apply_Call {
	_ = "STUB: not implemented"
	return nil

	// GetName provides a mock function with no fields
}

func (_m *CellWriter) GetName() string { _ = "STUB: not implemented"; return "" }

// CellWriter_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type CellWriter_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *CellWriter_Expecter) GetName() *CellWriter_GetName_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_GetName_Call) Run(run func()) *CellWriter_GetName_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_GetName_Call) Return(_a0 string) *CellWriter_GetName_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_GetName_Call) RunAndReturn(run func() string) *CellWriter_GetName_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNext provides a mock function with no fields
func (_m *CellWriter) GetNext() cellwriter.CellWriter {
	_ = "STUB: not implemented"
	return *new(cellwriter.CellWriter)
}

// CellWriter_GetNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNext'
type CellWriter_GetNext_Call struct {
	*mock.Call
}

// GetNext is a helper method to define mock.On call
func (_e *CellWriter_Expecter) GetNext() *CellWriter_GetNext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_GetNext_Call) Run(run func()) *CellWriter_GetNext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_GetNext_Call) Return(_a0 cellwriter.CellWriter) *CellWriter_GetNext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_GetNext_Call) RunAndReturn(run func() cellwriter.CellWriter) *CellWriter_GetNext_Call {
	_ = "STUB: not implemented"
	return nil
}

// SetNext provides a mock function with given fields: next
func (_m *CellWriter) SetNext(next cellwriter.CellWriter) {
	_ = "STUB: not implemented"

	// CellWriter_SetNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNext'
	return
}

type CellWriter_SetNext_Call struct {
	*mock.Call
}

// SetNext is a helper method to define mock.On call
//   - next cellwriter.CellWriter
func (_e *CellWriter_Expecter) SetNext(next interface{}) *CellWriter_SetNext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_SetNext_Call) Run(run func(next cellwriter.CellWriter)) *CellWriter_SetNext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_SetNext_Call) Return() *CellWriter_SetNext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CellWriter_SetNext_Call) RunAndReturn(run func(cellwriter.CellWriter)) *CellWriter_SetNext_Call {
	_ = "STUB: not implemented"
	return nil

	// NewCellWriter creates a new instance of CellWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
}

func NewCellWriter(t interface {
	mock.TestingT
	Cleanup(func())
},
) *CellWriter {
	_ = "STUB: not implemented"
	return nil
}
