// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"
	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// Checkbox is an autogenerated mock type for the Checkbox type
type Checkbox struct {
	mock.Mock
}

type Checkbox_Expecter struct {
	mock *mock.Mock
}

func (_m *Checkbox) EXPECT() *Checkbox_Expecter { _ = "STUB: not implemented"; return nil }

// Add provides a mock function with given fields: label, cell, prop
func (_m *Checkbox) Add(label string, cell *entity.Cell, prop *props.Checkbox) {
	_ = "STUB: not implemented"
	return
}

// Checkbox_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Checkbox_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - label string
//   - cell *entity.Cell
//   - prop *props.Checkbox
func (_e *Checkbox_Expecter) Add(label interface{}, cell interface{}, prop interface{}) *Checkbox_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Checkbox_Add_Call) Run(run func(label string, cell *entity.Cell, prop *props.Checkbox)) *Checkbox_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Checkbox_Add_Call) Return() *Checkbox_Add_Call { _ = "STUB: not implemented"; return nil }

func (_c *Checkbox_Add_Call) RunAndReturn(run func(string, *entity.Cell, *props.Checkbox)) *Checkbox_Add_Call {
	_ = "STUB: not implemented"
	return nil

	// NewCheckbox creates a new instance of Checkbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
}

func NewCheckbox(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Checkbox {
	_ = "STUB: not implemented"
	return nil
}
