// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"
	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// Code is an autogenerated mock type for the Code type
type Code struct {
	mock.Mock
}

type Code_Expecter struct {
	mock *mock.Mock
}

func (_m *Code) EXPECT() *Code_Expecter { _ = "STUB: not implemented"; return nil }

// GenBar provides a mock function with given fields: code, cell, prop
func (_m *Code) GenBar(code string, cell *entity.Cell, prop *props.Barcode) (*entity.Image, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Code_GenBar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenBar'
type Code_GenBar_Call struct {
	*mock.Call
}

// GenBar is a helper method to define mock.On call
//   - code string
//   - cell *entity.Cell
//   - prop *props.Barcode
func (_e *Code_Expecter) GenBar(code interface{}, cell interface{}, prop interface{}) *Code_GenBar_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenBar_Call) Run(run func(code string, cell *entity.Cell, prop *props.Barcode)) *Code_GenBar_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenBar_Call) Return(_a0 *entity.Image, _a1 error) *Code_GenBar_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenBar_Call) RunAndReturn(run func(string, *entity.Cell, *props.Barcode) (*entity.Image, error)) *Code_GenBar_Call {
	_ = "STUB: not implemented"
	return nil
}

// GenDataMatrix provides a mock function with given fields: code
func (_m *Code) GenDataMatrix(code string) (*entity.Image, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Code_GenDataMatrix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenDataMatrix'
type Code_GenDataMatrix_Call struct {
	*mock.Call
}

// GenDataMatrix is a helper method to define mock.On call
//   - code string
func (_e *Code_Expecter) GenDataMatrix(code interface{}) *Code_GenDataMatrix_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenDataMatrix_Call) Run(run func(code string)) *Code_GenDataMatrix_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenDataMatrix_Call) Return(_a0 *entity.Image, _a1 error) *Code_GenDataMatrix_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenDataMatrix_Call) RunAndReturn(run func(string) (*entity.Image, error)) *Code_GenDataMatrix_Call {
	_ = "STUB: not implemented"
	return nil
}

// GenQr provides a mock function with given fields: code
func (_m *Code) GenQr(code string) (*entity.Image, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Code_GenQr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenQr'
type Code_GenQr_Call struct {
	*mock.Call
}

// GenQr is a helper method to define mock.On call
//   - code string
func (_e *Code_Expecter) GenQr(code interface{}) *Code_GenQr_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenQr_Call) Run(run func(code string)) *Code_GenQr_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenQr_Call) Return(_a0 *entity.Image, _a1 error) *Code_GenQr_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Code_GenQr_Call) RunAndReturn(run func(string) (*entity.Image, error)) *Code_GenQr_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewCode creates a new instance of Code. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCode(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Code {
	_ = "STUB: not implemented"
	return nil
}
