// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	core "github.com/johnfercher/maroto/v2/pkg/core"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"

	node "github.com/johnfercher/go-tree/node"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// Col is an autogenerated mock type for the Col type
type Col struct {
	mock.Mock
}

type Col_Expecter struct {
	mock *mock.Mock
}

func (_m *Col) EXPECT() *Col_Expecter { _ = "STUB: not implemented"; return nil }

// Add provides a mock function with given fields: components
func (_m *Col) Add(components ...core.Component) core.Col {
	_ = "STUB: not implemented"
	return *new(core.Col)
}

// Col_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Col_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - components ...core.Component
func (_e *Col_Expecter) Add(components ...interface{}) *Col_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_Add_Call) Run(run func(components ...core.Component)) *Col_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_Add_Call) Return(_a0 core.Col) *Col_Add_Call { _ = "STUB: not implemented"; return nil }

func (_c *Col_Add_Call) RunAndReturn(run func(...core.Component) core.Col) *Col_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetHeight provides a mock function with given fields: provider, cell
func (_m *Col) GetHeight(provider core.Provider, cell *entity.Cell) float64 {
	_ = "STUB: not implemented"
	return 0
}

// Col_GetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeight'
type Col_GetHeight_Call struct {
	*mock.Call
}

// GetHeight is a helper method to define mock.On call
//   - provider core.Provider
//   - cell *entity.Cell
func (_e *Col_Expecter) GetHeight(provider interface{}, cell interface{}) *Col_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_GetHeight_Call) Run(run func(provider core.Provider, cell *entity.Cell)) *Col_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_GetHeight_Call) Return(_a0 float64) *Col_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_GetHeight_Call) RunAndReturn(run func(core.Provider, *entity.Cell) float64) *Col_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSize provides a mock function with no fields
func (_m *Col) GetSize() int { _ = "STUB: not implemented"; return 0 }

// Col_GetSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSize'
type Col_GetSize_Call struct {
	*mock.Call
}

// GetSize is a helper method to define mock.On call
func (_e *Col_Expecter) GetSize() *Col_GetSize_Call { _ = "STUB: not implemented"; return nil }

func (_c *Col_GetSize_Call) Run(run func()) *Col_GetSize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_GetSize_Call) Return(_a0 int) *Col_GetSize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_GetSize_Call) RunAndReturn(run func() int) *Col_GetSize_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStructure provides a mock function with no fields
func (_m *Col) GetStructure() *node.Node[core.Structure] { _ = "STUB: not implemented"; return nil }

// Col_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type Col_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *Col_Expecter) GetStructure() *Col_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_GetStructure_Call) Run(run func()) *Col_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_GetStructure_Call) Return(_a0 *node.Node[core.Structure]) *Col_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_GetStructure_Call) RunAndReturn(run func() *node.Node[core.Structure]) *Col_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

// Render provides a mock function with given fields: provider, cell, createCell
func (_m *Col) Render(provider core.Provider, cell entity.Cell, createCell bool) {
	_ = "STUB: not implemented"
	return
}

// Col_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Col_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - provider core.Provider
//   - cell entity.Cell
//   - createCell bool
func (_e *Col_Expecter) Render(provider interface{}, cell interface{}, createCell interface{}) *Col_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_Render_Call) Run(run func(provider core.Provider, cell entity.Cell, createCell bool)) *Col_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_Render_Call) Return() *Col_Render_Call { _ = "STUB: not implemented"; return nil }

func (_c *Col_Render_Call) RunAndReturn(run func(core.Provider, entity.Cell, bool)) *Col_Render_Call {
	_ = "STUB: not implemented"
	return nil

	// SetConfig provides a mock function with given fields: config
}

func (_m *Col) SetConfig(config *entity.Config) {
	_ = "STUB: not implemented"

	// Col_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
	return
}

type Col_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - config *entity.Config
func (_e *Col_Expecter) SetConfig(config interface{}) *Col_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_SetConfig_Call) Run(run func(config *entity.Config)) *Col_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_SetConfig_Call) Return() *Col_SetConfig_Call { _ = "STUB: not implemented"; return nil }

func (_c *Col_SetConfig_Call) RunAndReturn(run func(*entity.Config)) *Col_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil

	// WithStyle provides a mock function with given fields: style
}

func (_m *Col) WithStyle(style *props.Cell) core.Col {
	_ = "STUB: not implemented"
	return *new(core.Col)
}

// Col_WithStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithStyle'
type Col_WithStyle_Call struct {
	*mock.Call
}

// WithStyle is a helper method to define mock.On call
//   - style *props.Cell
func (_e *Col_Expecter) WithStyle(style interface{}) *Col_WithStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_WithStyle_Call) Run(run func(style *props.Cell)) *Col_WithStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_WithStyle_Call) Return(_a0 core.Col) *Col_WithStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Col_WithStyle_Call) RunAndReturn(run func(*props.Cell) core.Col) *Col_WithStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewCol creates a new instance of Col. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCol(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Col {
	_ = "STUB: not implemented"
	return nil
}
