// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	core "github.com/johnfercher/maroto/v2/pkg/core"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"

	node "github.com/johnfercher/go-tree/node"
)

// Component is an autogenerated mock type for the Component type
type Component struct {
	mock.Mock
}

type Component_Expecter struct {
	mock *mock.Mock
}

func (_m *Component) EXPECT() *Component_Expecter { _ = "STUB: not implemented"; return nil }

// GetHeight provides a mock function with given fields: provider, cell
func (_m *Component) GetHeight(provider core.Provider, cell *entity.Cell) float64 {
	_ = "STUB: not implemented"
	return 0
}

// Component_GetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeight'
type Component_GetHeight_Call struct {
	*mock.Call
}

// GetHeight is a helper method to define mock.On call
//   - provider core.Provider
//   - cell *entity.Cell
func (_e *Component_Expecter) GetHeight(provider interface{}, cell interface{}) *Component_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_GetHeight_Call) Run(run func(provider core.Provider, cell *entity.Cell)) *Component_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_GetHeight_Call) Return(_a0 float64) *Component_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_GetHeight_Call) RunAndReturn(run func(core.Provider, *entity.Cell) float64) *Component_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStructure provides a mock function with no fields
func (_m *Component) GetStructure() *node.Node[core.Structure] {
	_ = "STUB: not implemented"
	return nil
}

// Component_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type Component_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *Component_Expecter) GetStructure() *Component_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_GetStructure_Call) Run(run func()) *Component_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_GetStructure_Call) Return(_a0 *node.Node[core.Structure]) *Component_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_GetStructure_Call) RunAndReturn(run func() *node.Node[core.Structure]) *Component_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

// Render provides a mock function with given fields: provider, cell
func (_m *Component) Render(provider core.Provider, cell *entity.Cell) {
	_ = "STUB: not implemented"
	return
}

// Component_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Component_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - provider core.Provider
//   - cell *entity.Cell
func (_e *Component_Expecter) Render(provider interface{}, cell interface{}) *Component_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_Render_Call) Run(run func(provider core.Provider, cell *entity.Cell)) *Component_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_Render_Call) Return() *Component_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_Render_Call) RunAndReturn(run func(core.Provider, *entity.Cell)) *Component_Render_Call {
	_ = "STUB: not implemented"
	return nil

	// SetConfig provides a mock function with given fields: config
}

func (_m *Component) SetConfig(config *entity.Config) {
	_ = "STUB: not implemented"

	// Component_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
	return
}

type Component_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - config *entity.Config
func (_e *Component_Expecter) SetConfig(config interface{}) *Component_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_SetConfig_Call) Run(run func(config *entity.Config)) *Component_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_SetConfig_Call) Return() *Component_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Component_SetConfig_Call) RunAndReturn(run func(*entity.Config)) *Component_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil

	// NewComponent creates a new instance of Component. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
}

func NewComponent(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Component {
	_ = "STUB: not implemented"
	return nil
}
