// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	fontstyle "github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	mock "github.com/stretchr/testify/mock"
)

// CustomFont is an autogenerated mock type for the CustomFont type
type CustomFont struct {
	mock.Mock
}

type CustomFont_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomFont) EXPECT() *CustomFont_Expecter { _ = "STUB: not implemented"; return nil }

// GetBytes provides a mock function with no fields
func (_m *CustomFont) GetBytes() []byte { _ = "STUB: not implemented"; return nil }

// CustomFont_GetBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBytes'
type CustomFont_GetBytes_Call struct {
	*mock.Call
}

// GetBytes is a helper method to define mock.On call
func (_e *CustomFont_Expecter) GetBytes() *CustomFont_GetBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetBytes_Call) Run(run func()) *CustomFont_GetBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetBytes_Call) Return(_a0 []byte) *CustomFont_GetBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetBytes_Call) RunAndReturn(run func() []byte) *CustomFont_GetBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFamily provides a mock function with no fields
func (_m *CustomFont) GetFamily() string { _ = "STUB: not implemented"; return "" }

// CustomFont_GetFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamily'
type CustomFont_GetFamily_Call struct {
	*mock.Call
}

// GetFamily is a helper method to define mock.On call
func (_e *CustomFont_Expecter) GetFamily() *CustomFont_GetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetFamily_Call) Run(run func()) *CustomFont_GetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetFamily_Call) Return(_a0 string) *CustomFont_GetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetFamily_Call) RunAndReturn(run func() string) *CustomFont_GetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFile provides a mock function with no fields
func (_m *CustomFont) GetFile() string { _ = "STUB: not implemented"; return "" }

// CustomFont_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type CustomFont_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
func (_e *CustomFont_Expecter) GetFile() *CustomFont_GetFile_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetFile_Call) Run(run func()) *CustomFont_GetFile_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetFile_Call) Return(_a0 string) *CustomFont_GetFile_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetFile_Call) RunAndReturn(run func() string) *CustomFont_GetFile_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStyle provides a mock function with no fields
func (_m *CustomFont) GetStyle() fontstyle.Type {
	_ = "STUB: not implemented"
	return *new(fontstyle.Type)
}

// CustomFont_GetStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStyle'
type CustomFont_GetStyle_Call struct {
	*mock.Call
}

// GetStyle is a helper method to define mock.On call
func (_e *CustomFont_Expecter) GetStyle() *CustomFont_GetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetStyle_Call) Run(run func()) *CustomFont_GetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetStyle_Call) Return(_a0 fontstyle.Type) *CustomFont_GetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *CustomFont_GetStyle_Call) RunAndReturn(run func() fontstyle.Type) *CustomFont_GetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewCustomFont creates a new instance of CustomFont. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomFont(t interface {
	mock.TestingT
	Cleanup(func())
},
) *CustomFont {
	_ = "STUB: not implemented"
	return nil
}
