// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	metrics "github.com/johnfercher/maroto/v2/pkg/metrics"
	mock "github.com/stretchr/testify/mock"
)

// Document is an autogenerated mock type for the Document type
type Document struct {
	mock.Mock
}

type Document_Expecter struct {
	mock *mock.Mock
}

func (_m *Document) EXPECT() *Document_Expecter { _ = "STUB: not implemented"; return nil }

// GetBase64 provides a mock function with no fields
func (_m *Document) GetBase64() string { _ = "STUB: not implemented"; return "" }

// Document_GetBase64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBase64'
type Document_GetBase64_Call struct {
	*mock.Call
}

// GetBase64 is a helper method to define mock.On call
func (_e *Document_Expecter) GetBase64() *Document_GetBase64_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetBase64_Call) Run(run func()) *Document_GetBase64_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetBase64_Call) Return(_a0 string) *Document_GetBase64_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetBase64_Call) RunAndReturn(run func() string) *Document_GetBase64_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBytes provides a mock function with no fields
func (_m *Document) GetBytes() []byte { _ = "STUB: not implemented"; return nil }

// Document_GetBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBytes'
type Document_GetBytes_Call struct {
	*mock.Call
}

// GetBytes is a helper method to define mock.On call
func (_e *Document_Expecter) GetBytes() *Document_GetBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetBytes_Call) Run(run func()) *Document_GetBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetBytes_Call) Return(_a0 []byte) *Document_GetBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetBytes_Call) RunAndReturn(run func() []byte) *Document_GetBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetReport provides a mock function with no fields
func (_m *Document) GetReport() *metrics.Report { _ = "STUB: not implemented"; return nil }

// Document_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type Document_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
func (_e *Document_Expecter) GetReport() *Document_GetReport_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetReport_Call) Run(run func()) *Document_GetReport_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetReport_Call) Return(_a0 *metrics.Report) *Document_GetReport_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_GetReport_Call) RunAndReturn(run func() *metrics.Report) *Document_GetReport_Call {
	_ = "STUB: not implemented"
	return nil
}

// Merge provides a mock function with given fields: bytes
func (_m *Document) Merge(bytes []byte) error { _ = "STUB: not implemented"; return nil }

// Document_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type Document_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - bytes []byte
func (_e *Document_Expecter) Merge(bytes interface{}) *Document_Merge_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_Merge_Call) Run(run func(bytes []byte)) *Document_Merge_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_Merge_Call) Return(_a0 error) *Document_Merge_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_Merge_Call) RunAndReturn(run func([]byte) error) *Document_Merge_Call {
	_ = "STUB: not implemented"
	return nil
}

// Save provides a mock function with given fields: file
func (_m *Document) Save(file string) error { _ = "STUB: not implemented"; return nil }

// Document_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Document_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - file string
func (_e *Document_Expecter) Save(file interface{}) *Document_Save_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_Save_Call) Run(run func(file string)) *Document_Save_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_Save_Call) Return(_a0 error) *Document_Save_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Document_Save_Call) RunAndReturn(run func(string) error) *Document_Save_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewDocument creates a new instance of Document. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocument(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Document {
	_ = "STUB: not implemented"
	return nil
}
