// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	fontstyle "github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// Font is an autogenerated mock type for the Font type
type Font struct {
	mock.Mock
}

type Font_Expecter struct {
	mock *mock.Mock
}

func (_m *Font) EXPECT() *Font_Expecter { _ = "STUB: not implemented"; return nil }

// GetColor provides a mock function with no fields
func (_m *Font) GetColor() *props.Color { _ = "STUB: not implemented"; return nil }

// Font_GetColor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetColor'
type Font_GetColor_Call struct {
	*mock.Call
}

// GetColor is a helper method to define mock.On call
func (_e *Font_Expecter) GetColor() *Font_GetColor_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_GetColor_Call) Run(run func()) *Font_GetColor_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetColor_Call) Return(_a0 *props.Color) *Font_GetColor_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetColor_Call) RunAndReturn(run func() *props.Color) *Font_GetColor_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFamily provides a mock function with no fields
func (_m *Font) GetFamily() string { _ = "STUB: not implemented"; return "" }

// Font_GetFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamily'
type Font_GetFamily_Call struct {
	*mock.Call
}

// GetFamily is a helper method to define mock.On call
func (_e *Font_Expecter) GetFamily() *Font_GetFamily_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_GetFamily_Call) Run(run func()) *Font_GetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetFamily_Call) Return(_a0 string) *Font_GetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetFamily_Call) RunAndReturn(run func() string) *Font_GetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFont provides a mock function with no fields
func (_m *Font) GetFont() (string, fontstyle.Type, float64) {
	_ = "STUB: not implemented"
	return "", *new(fontstyle.Type), 0
}

// Font_GetFont_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFont'
type Font_GetFont_Call struct {
	*mock.Call
}

// GetFont is a helper method to define mock.On call
func (_e *Font_Expecter) GetFont() *Font_GetFont_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_GetFont_Call) Run(run func()) *Font_GetFont_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetFont_Call) Return(_a0 string, _a1 fontstyle.Type, _a2 float64) *Font_GetFont_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetFont_Call) RunAndReturn(run func() (string, fontstyle.Type, float64)) *Font_GetFont_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetHeight provides a mock function with given fields: family, style, size
func (_m *Font) GetHeight(family string, style fontstyle.Type, size float64) float64 {
	_ = "STUB: not implemented"
	return 0
}

// Font_GetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeight'
type Font_GetHeight_Call struct {
	*mock.Call
}

// GetHeight is a helper method to define mock.On call
//   - family string
//   - style fontstyle.Type
//   - size float64
func (_e *Font_Expecter) GetHeight(family interface{}, style interface{}, size interface{}) *Font_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetHeight_Call) Run(run func(family string, style fontstyle.Type, size float64)) *Font_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetHeight_Call) Return(_a0 float64) *Font_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetHeight_Call) RunAndReturn(run func(string, fontstyle.Type, float64) float64) *Font_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSize provides a mock function with no fields
func (_m *Font) GetSize() float64 { _ = "STUB: not implemented"; return 0 }

// Font_GetSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSize'
type Font_GetSize_Call struct {
	*mock.Call
}

// GetSize is a helper method to define mock.On call
func (_e *Font_Expecter) GetSize() *Font_GetSize_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_GetSize_Call) Run(run func()) *Font_GetSize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetSize_Call) Return(_a0 float64) *Font_GetSize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetSize_Call) RunAndReturn(run func() float64) *Font_GetSize_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStyle provides a mock function with no fields
func (_m *Font) GetStyle() fontstyle.Type { _ = "STUB: not implemented"; return *new(fontstyle.Type) }

// Font_GetStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStyle'
type Font_GetStyle_Call struct {
	*mock.Call
}

// GetStyle is a helper method to define mock.On call
func (_e *Font_Expecter) GetStyle() *Font_GetStyle_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_GetStyle_Call) Run(run func()) *Font_GetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetStyle_Call) Return(_a0 fontstyle.Type) *Font_GetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_GetStyle_Call) RunAndReturn(run func() fontstyle.Type) *Font_GetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

// SetColor provides a mock function with given fields: color
func (_m *Font) SetColor(color *props.Color) {
	_ = "STUB: not implemented"

	// Font_SetColor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetColor'
	return
}

type Font_SetColor_Call struct {
	*mock.Call
}

// SetColor is a helper method to define mock.On call
//   - color *props.Color
func (_e *Font_Expecter) SetColor(color interface{}) *Font_SetColor_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetColor_Call) Run(run func(color *props.Color)) *Font_SetColor_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetColor_Call) Return() *Font_SetColor_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_SetColor_Call) RunAndReturn(run func(*props.Color)) *Font_SetColor_Call {
	_ = "STUB: not implemented"
	return nil

	// SetFamily provides a mock function with given fields: family
}

func (_m *Font) SetFamily(family string) {
	_ = "STUB: not implemented"

	// Font_SetFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFamily'
	return
}

type Font_SetFamily_Call struct {
	*mock.Call
}

// SetFamily is a helper method to define mock.On call
//   - family string
func (_e *Font_Expecter) SetFamily(family interface{}) *Font_SetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetFamily_Call) Run(run func(family string)) *Font_SetFamily_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetFamily_Call) Return() *Font_SetFamily_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_SetFamily_Call) RunAndReturn(run func(string)) *Font_SetFamily_Call {
	_ = "STUB: not implemented"
	return nil

	// SetFont provides a mock function with given fields: family, style, size
}

func (_m *Font) SetFont(family string, style fontstyle.Type, size float64) {
	_ = "STUB: not implemented"
	return
}

// Font_SetFont_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFont'
type Font_SetFont_Call struct {
	*mock.Call
}

// SetFont is a helper method to define mock.On call
//   - family string
//   - style fontstyle.Type
//   - size float64
func (_e *Font_Expecter) SetFont(family interface{}, style interface{}, size interface{}) *Font_SetFont_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetFont_Call) Run(run func(family string, style fontstyle.Type, size float64)) *Font_SetFont_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetFont_Call) Return() *Font_SetFont_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_SetFont_Call) RunAndReturn(run func(string, fontstyle.Type, float64)) *Font_SetFont_Call {
	_ = "STUB: not implemented"
	return nil

	// SetSize provides a mock function with given fields: size
}

func (_m *Font) SetSize(size float64) {
	_ = "STUB: not implemented"

	// Font_SetSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSize'
	return
}

type Font_SetSize_Call struct {
	*mock.Call
}

// SetSize is a helper method to define mock.On call
//   - size float64
func (_e *Font_Expecter) SetSize(size interface{}) *Font_SetSize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetSize_Call) Run(run func(size float64)) *Font_SetSize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetSize_Call) Return() *Font_SetSize_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_SetSize_Call) RunAndReturn(run func(float64)) *Font_SetSize_Call {
	_ = "STUB: not implemented"
	return nil

	// SetStyle provides a mock function with given fields: style
}

func (_m *Font) SetStyle(style fontstyle.Type) {
	_ = "STUB: not implemented"

	// Font_SetStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStyle'
	return
}

type Font_SetStyle_Call struct {
	*mock.Call
}

// SetStyle is a helper method to define mock.On call
//   - style fontstyle.Type
func (_e *Font_Expecter) SetStyle(style interface{}) *Font_SetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetStyle_Call) Run(run func(style fontstyle.Type)) *Font_SetStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Font_SetStyle_Call) Return() *Font_SetStyle_Call { _ = "STUB: not implemented"; return nil }

func (_c *Font_SetStyle_Call) RunAndReturn(run func(fontstyle.Type)) *Font_SetStyle_Call {
	_ = "STUB: not implemented"
	return nil

	// NewFont creates a new instance of Font. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
}

func NewFont(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Font {
	_ = "STUB: not implemented"
	return nil
}
