// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	extension "github.com/johnfercher/maroto/v2/pkg/consts/extension"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	gofpdf "github.com/phpdave11/gofpdf"

	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/v2/pkg/props"

	uuid "github.com/google/uuid"
)

// Image is an autogenerated mock type for the Image type
type Image struct {
	mock.Mock
}

type Image_Expecter struct {
	mock *mock.Mock
}

func (_m *Image) EXPECT() *Image_Expecter { _ = "STUB: not implemented"; return nil }

// Add provides a mock function with given fields: img, cell, margins, prop, _a4, flow
func (_m *Image) Add(img *entity.Image, cell *entity.Cell, margins *entity.Margins, prop *props.Rect, _a4 extension.Type, flow bool) error {
	_ = "STUB: not implemented"
	return nil
}

// Image_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Image_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - img *entity.Image
//   - cell *entity.Cell
//   - margins *entity.Margins
//   - prop *props.Rect
//   - _a4 extension.Type
//   - flow bool
func (_e *Image_Expecter) Add(img interface{}, cell interface{}, margins interface{}, prop interface{}, _a4 interface{}, flow interface{}) *Image_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Image_Add_Call) Run(run func(img *entity.Image, cell *entity.Cell, margins *entity.Margins, prop *props.Rect, _a4 extension.Type, flow bool)) *Image_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Image_Add_Call) Return(_a0 error) *Image_Add_Call { _ = "STUB: not implemented"; return nil }

func (_c *Image_Add_Call) RunAndReturn(run func(*entity.Image, *entity.Cell, *entity.Margins, *props.Rect, extension.Type, bool) error) *Image_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetImageInfo provides a mock function with given fields: img, _a1
func (_m *Image) GetImageInfo(img *entity.Image, _a1 extension.Type) (*gofpdf.ImageInfoType, uuid.UUID) {
	_ = "STUB: not implemented"
	return nil, *new(uuid.UUID)
}

// Image_GetImageInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageInfo'
type Image_GetImageInfo_Call struct {
	*mock.Call
}

// GetImageInfo is a helper method to define mock.On call
//   - img *entity.Image
//   - _a1 extension.Type
func (_e *Image_Expecter) GetImageInfo(img interface{}, _a1 interface{}) *Image_GetImageInfo_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Image_GetImageInfo_Call) Run(run func(img *entity.Image, _a1 extension.Type)) *Image_GetImageInfo_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Image_GetImageInfo_Call) Return(_a0 *gofpdf.ImageInfoType, _a1 uuid.UUID) *Image_GetImageInfo_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Image_GetImageInfo_Call) RunAndReturn(run func(*entity.Image, extension.Type) (*gofpdf.ImageInfoType, uuid.UUID)) *Image_GetImageInfo_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewImage creates a new instance of Image. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImage(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Image {
	_ = "STUB: not implemented"
	return nil
}
