// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"
	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// Line is an autogenerated mock type for the Line type
type Line struct {
	mock.Mock
}

type Line_Expecter struct {
	mock *mock.Mock
}

func (_m *Line) EXPECT() *Line_Expecter { _ = "STUB: not implemented"; return nil }

// Add provides a mock function with given fields: cell, prop
func (_m *Line) Add(cell *entity.Cell, prop *props.Line) { _ = "STUB: not implemented"; return }

// Line_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Line_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - cell *entity.Cell
//   - prop *props.Line
func (_e *Line_Expecter) Add(cell interface{}, prop interface{}) *Line_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Line_Add_Call) Run(run func(cell *entity.Cell, prop *props.Line)) *Line_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Line_Add_Call) Return() *Line_Add_Call { _ = "STUB: not implemented"; return nil }

func (_c *Line_Add_Call) RunAndReturn(run func(*entity.Cell, *props.Line)) *Line_Add_Call {
	_ = "STUB: not implemented"
	return nil

	// NewLine creates a new instance of Line. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
}

func NewLine(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Line {
	_ = "STUB: not implemented"
	return nil
}
