// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	core "github.com/johnfercher/maroto/v2/pkg/core"

	mock "github.com/stretchr/testify/mock"
)

// Listable is an autogenerated mock type for the Listable type
type Listable struct {
	mock.Mock
}

type Listable_Expecter struct {
	mock *mock.Mock
}

func (_m *Listable) EXPECT() *Listable_Expecter { _ = "STUB: not implemented"; return nil }

// GetContent provides a mock function with given fields: i
func (_m *Listable) GetContent(i int) core.Row { _ = "STUB: not implemented"; return *new(core.Row) }

// Listable_GetContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContent'
type Listable_GetContent_Call struct {
	*mock.Call
}

// GetContent is a helper method to define mock.On call
//   - i int
func (_e *Listable_Expecter) GetContent(i interface{}) *Listable_GetContent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Listable_GetContent_Call) Run(run func(i int)) *Listable_GetContent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Listable_GetContent_Call) Return(_a0 core.Row) *Listable_GetContent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Listable_GetContent_Call) RunAndReturn(run func(int) core.Row) *Listable_GetContent_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetHeader provides a mock function with no fields
func (_m *Listable) GetHeader() core.Row { _ = "STUB: not implemented"; return *new(core.Row) }

// Listable_GetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeader'
type Listable_GetHeader_Call struct {
	*mock.Call
}

// GetHeader is a helper method to define mock.On call
func (_e *Listable_Expecter) GetHeader() *Listable_GetHeader_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Listable_GetHeader_Call) Run(run func()) *Listable_GetHeader_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Listable_GetHeader_Call) Return(_a0 core.Row) *Listable_GetHeader_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Listable_GetHeader_Call) RunAndReturn(run func() core.Row) *Listable_GetHeader_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewListable creates a new instance of Listable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListable(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Listable {
	_ = "STUB: not implemented"
	return nil
}
