// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	core "github.com/johnfercher/maroto/v2/pkg/core"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"

	node "github.com/johnfercher/go-tree/node"
)

// Maroto is an autogenerated mock type for the Maroto type
type Maroto struct {
	mock.Mock
}

type Maroto_Expecter struct {
	mock *mock.Mock
}

func (_m *Maroto) EXPECT() *Maroto_Expecter { _ = "STUB: not implemented"; return nil }

// AddAutoRow provides a mock function with given fields: cols
func (_m *Maroto) AddAutoRow(cols ...core.Col) core.Row {
	_ = "STUB: not implemented"
	return *new(core.Row)
}

// Maroto_AddAutoRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAutoRow'
type Maroto_AddAutoRow_Call struct {
	*mock.Call
}

// AddAutoRow is a helper method to define mock.On call
//   - cols ...core.Col
func (_e *Maroto_Expecter) AddAutoRow(cols ...interface{}) *Maroto_AddAutoRow_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddAutoRow_Call) Run(run func(cols ...core.Col)) *Maroto_AddAutoRow_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddAutoRow_Call) Return(_a0 core.Row) *Maroto_AddAutoRow_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddAutoRow_Call) RunAndReturn(run func(...core.Col) core.Row) *Maroto_AddAutoRow_Call {
	_ = "STUB: not implemented"
	return nil
}

// AddPages provides a mock function with given fields: pages
func (_m *Maroto) AddPages(pages ...core.Page) { _ = "STUB: not implemented"; return }

// Maroto_AddPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPages'
type Maroto_AddPages_Call struct {
	*mock.Call
}

// AddPages is a helper method to define mock.On call
//   - pages ...core.Page
func (_e *Maroto_Expecter) AddPages(pages ...interface{}) *Maroto_AddPages_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddPages_Call) Run(run func(pages ...core.Page)) *Maroto_AddPages_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddPages_Call) Return() *Maroto_AddPages_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddPages_Call) RunAndReturn(run func(...core.Page)) *Maroto_AddPages_Call {
	_ = "STUB: not implemented"
	return nil

	// AddRow provides a mock function with given fields: rowHeight, cols
}

func (_m *Maroto) AddRow(rowHeight float64, cols ...core.Col) core.Row {
	_ = "STUB: not implemented"
	return *new(core.Row)
}

// Maroto_AddRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRow'
type Maroto_AddRow_Call struct {
	*mock.Call
}

// AddRow is a helper method to define mock.On call
//   - rowHeight float64
//   - cols ...core.Col
func (_e *Maroto_Expecter) AddRow(rowHeight interface{}, cols ...interface{}) *Maroto_AddRow_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddRow_Call) Run(run func(rowHeight float64, cols ...core.Col)) *Maroto_AddRow_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddRow_Call) Return(_a0 core.Row) *Maroto_AddRow_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddRow_Call) RunAndReturn(run func(float64, ...core.Col) core.Row) *Maroto_AddRow_Call {
	_ = "STUB: not implemented"
	return nil
}

// AddRows provides a mock function with given fields: rows
func (_m *Maroto) AddRows(rows ...core.Row) { _ = "STUB: not implemented"; return }

// Maroto_AddRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRows'
type Maroto_AddRows_Call struct {
	*mock.Call
}

// AddRows is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *Maroto_Expecter) AddRows(rows ...interface{}) *Maroto_AddRows_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddRows_Call) Run(run func(rows ...core.Row)) *Maroto_AddRows_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_AddRows_Call) Return() *Maroto_AddRows_Call { _ = "STUB: not implemented"; return nil }

func (_c *Maroto_AddRows_Call) RunAndReturn(run func(...core.Row)) *Maroto_AddRows_Call {
	_ = "STUB: not implemented"
	return nil

	// FitlnCurrentPage provides a mock function with given fields: heightNewLine
}

func (_m *Maroto) FitlnCurrentPage(heightNewLine float64) bool {
	_ = "STUB: not implemented"
	return false
}

// Maroto_FitlnCurrentPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FitlnCurrentPage'
type Maroto_FitlnCurrentPage_Call struct {
	*mock.Call
}

// FitlnCurrentPage is a helper method to define mock.On call
//   - heightNewLine float64
func (_e *Maroto_Expecter) FitlnCurrentPage(heightNewLine interface{}) *Maroto_FitlnCurrentPage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_FitlnCurrentPage_Call) Run(run func(heightNewLine float64)) *Maroto_FitlnCurrentPage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_FitlnCurrentPage_Call) Return(_a0 bool) *Maroto_FitlnCurrentPage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_FitlnCurrentPage_Call) RunAndReturn(run func(float64) bool) *Maroto_FitlnCurrentPage_Call {
	_ = "STUB: not implemented"
	return nil
}

// Generate provides a mock function with no fields
func (_m *Maroto) Generate() (core.Document, error) {
	_ = "STUB: not implemented"
	return *new(core.Document), nil
}

// Maroto_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Maroto_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *Maroto_Expecter) Generate() *Maroto_Generate_Call { _ = "STUB: not implemented"; return nil }

func (_c *Maroto_Generate_Call) Run(run func()) *Maroto_Generate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_Generate_Call) Return(_a0 core.Document, _a1 error) *Maroto_Generate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_Generate_Call) RunAndReturn(run func() (core.Document, error)) *Maroto_Generate_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCurrentConfig provides a mock function with no fields
func (_m *Maroto) GetCurrentConfig() *entity.Config { _ = "STUB: not implemented"; return nil }

// Maroto_GetCurrentConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentConfig'
type Maroto_GetCurrentConfig_Call struct {
	*mock.Call
}

// GetCurrentConfig is a helper method to define mock.On call
func (_e *Maroto_Expecter) GetCurrentConfig() *Maroto_GetCurrentConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_GetCurrentConfig_Call) Run(run func()) *Maroto_GetCurrentConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_GetCurrentConfig_Call) Return(_a0 *entity.Config) *Maroto_GetCurrentConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_GetCurrentConfig_Call) RunAndReturn(run func() *entity.Config) *Maroto_GetCurrentConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStructure provides a mock function with no fields
func (_m *Maroto) GetStructure() *node.Node[core.Structure] { _ = "STUB: not implemented"; return nil }

// Maroto_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type Maroto_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *Maroto_Expecter) GetStructure() *Maroto_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_GetStructure_Call) Run(run func()) *Maroto_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_GetStructure_Call) Return(_a0 *node.Node[core.Structure]) *Maroto_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_GetStructure_Call) RunAndReturn(run func() *node.Node[core.Structure]) *Maroto_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterFooter provides a mock function with given fields: rows
func (_m *Maroto) RegisterFooter(rows ...core.Row) error { _ = "STUB: not implemented"; return nil }

// Maroto_RegisterFooter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFooter'
type Maroto_RegisterFooter_Call struct {
	*mock.Call
}

// RegisterFooter is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *Maroto_Expecter) RegisterFooter(rows ...interface{}) *Maroto_RegisterFooter_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_RegisterFooter_Call) Run(run func(rows ...core.Row)) *Maroto_RegisterFooter_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_RegisterFooter_Call) Return(_a0 error) *Maroto_RegisterFooter_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_RegisterFooter_Call) RunAndReturn(run func(...core.Row) error) *Maroto_RegisterFooter_Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterHeader provides a mock function with given fields: rows
func (_m *Maroto) RegisterHeader(rows ...core.Row) error { _ = "STUB: not implemented"; return nil }

// Maroto_RegisterHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHeader'
type Maroto_RegisterHeader_Call struct {
	*mock.Call
}

// RegisterHeader is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *Maroto_Expecter) RegisterHeader(rows ...interface{}) *Maroto_RegisterHeader_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_RegisterHeader_Call) Run(run func(rows ...core.Row)) *Maroto_RegisterHeader_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_RegisterHeader_Call) Return(_a0 error) *Maroto_RegisterHeader_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Maroto_RegisterHeader_Call) RunAndReturn(run func(...core.Row) error) *Maroto_RegisterHeader_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMaroto creates a new instance of Maroto. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaroto(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Maroto {
	_ = "STUB: not implemented"
	return nil
}
