// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"
	mock "github.com/stretchr/testify/mock"
)

// Math is an autogenerated mock type for the Math type
type Math struct {
	mock.Mock
}

type Math_Expecter struct {
	mock *mock.Mock
}

func (_m *Math) EXPECT() *Math_Expecter { _ = "STUB: not implemented"; return nil }

// GetInnerCenterCell provides a mock function with given fields: inner, outer
func (_m *Math) GetInnerCenterCell(inner *entity.Dimensions, outer *entity.Dimensions) *entity.Cell {
	_ = "STUB: not implemented"
	return nil
}

// Math_GetInnerCenterCell_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInnerCenterCell'
type Math_GetInnerCenterCell_Call struct {
	*mock.Call
}

// GetInnerCenterCell is a helper method to define mock.On call
//   - inner *entity.Dimensions
//   - outer *entity.Dimensions
func (_e *Math_Expecter) GetInnerCenterCell(inner interface{}, outer interface{}) *Math_GetInnerCenterCell_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Math_GetInnerCenterCell_Call) Run(run func(inner *entity.Dimensions, outer *entity.Dimensions)) *Math_GetInnerCenterCell_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Math_GetInnerCenterCell_Call) Return(_a0 *entity.Cell) *Math_GetInnerCenterCell_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Math_GetInnerCenterCell_Call) RunAndReturn(run func(*entity.Dimensions, *entity.Dimensions) *entity.Cell) *Math_GetInnerCenterCell_Call {
	_ = "STUB: not implemented"
	return nil
}

// Resize provides a mock function with given fields: inner, outer, percent, justReferenceWidth
func (_m *Math) Resize(inner *entity.Dimensions, outer *entity.Dimensions, percent float64, justReferenceWidth bool) *entity.Dimensions {
	_ = "STUB: not implemented"
	return nil
}

// Math_Resize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resize'
type Math_Resize_Call struct {
	*mock.Call
}

// Resize is a helper method to define mock.On call
//   - inner *entity.Dimensions
//   - outer *entity.Dimensions
//   - percent float64
//   - justReferenceWidth bool
func (_e *Math_Expecter) Resize(inner interface{}, outer interface{}, percent interface{}, justReferenceWidth interface{}) *Math_Resize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Math_Resize_Call) Run(run func(inner *entity.Dimensions, outer *entity.Dimensions, percent float64, justReferenceWidth bool)) *Math_Resize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Math_Resize_Call) Return(_a0 *entity.Dimensions) *Math_Resize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Math_Resize_Call) RunAndReturn(run func(*entity.Dimensions, *entity.Dimensions, float64, bool) *entity.Dimensions) *Math_Resize_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMath creates a new instance of Math. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMath(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Math {
	_ = "STUB: not implemented"
	return nil
}
