// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	core "github.com/johnfercher/maroto/v2/pkg/core"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"

	node "github.com/johnfercher/go-tree/node"
)

// Node is an autogenerated mock type for the Node type
type Node struct {
	mock.Mock
}

type Node_Expecter struct {
	mock *mock.Mock
}

func (_m *Node) EXPECT() *Node_Expecter { _ = "STUB: not implemented"; return nil }

// GetStructure provides a mock function with no fields
func (_m *Node) GetStructure() *node.Node[core.Structure] { _ = "STUB: not implemented"; return nil }

// Node_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type Node_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *Node_Expecter) GetStructure() *Node_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Node_GetStructure_Call) Run(run func()) *Node_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Node_GetStructure_Call) Return(_a0 *node.Node[core.Structure]) *Node_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Node_GetStructure_Call) RunAndReturn(run func() *node.Node[core.Structure]) *Node_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

// SetConfig provides a mock function with given fields: config
func (_m *Node) SetConfig(config *entity.Config) {
	_ = "STUB: not implemented"

	// Node_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
	return
}

type Node_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - config *entity.Config
func (_e *Node_Expecter) SetConfig(config interface{}) *Node_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Node_SetConfig_Call) Run(run func(config *entity.Config)) *Node_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Node_SetConfig_Call) Return() *Node_SetConfig_Call { _ = "STUB: not implemented"; return nil }

func (_c *Node_SetConfig_Call) RunAndReturn(run func(*entity.Config)) *Node_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil

	// NewNode creates a new instance of Node. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
}

func NewNode(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Node {
	_ = "STUB: not implemented"
	return nil
}
