// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	core "github.com/johnfercher/maroto/v2/pkg/core"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"

	node "github.com/johnfercher/go-tree/node"
)

// Page is an autogenerated mock type for the Page type
type Page struct {
	mock.Mock
}

type Page_Expecter struct {
	mock *mock.Mock
}

func (_m *Page) EXPECT() *Page_Expecter { _ = "STUB: not implemented"; return nil }

// Add provides a mock function with given fields: rows
func (_m *Page) Add(rows ...core.Row) core.Page { _ = "STUB: not implemented"; return *new(core.Page) }

// Page_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Page_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - rows ...core.Row
func (_e *Page_Expecter) Add(rows ...interface{}) *Page_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_Add_Call) Run(run func(rows ...core.Row)) *Page_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_Add_Call) Return(_a0 core.Page) *Page_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_Add_Call) RunAndReturn(run func(...core.Row) core.Page) *Page_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNumber provides a mock function with no fields
func (_m *Page) GetNumber() int { _ = "STUB: not implemented"; return 0 }

// Page_GetNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNumber'
type Page_GetNumber_Call struct {
	*mock.Call
}

// GetNumber is a helper method to define mock.On call
func (_e *Page_Expecter) GetNumber() *Page_GetNumber_Call { _ = "STUB: not implemented"; return nil }

func (_c *Page_GetNumber_Call) Run(run func()) *Page_GetNumber_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_GetNumber_Call) Return(_a0 int) *Page_GetNumber_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_GetNumber_Call) RunAndReturn(run func() int) *Page_GetNumber_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRows provides a mock function with no fields
func (_m *Page) GetRows() []core.Row { _ = "STUB: not implemented"; return nil }

// Page_GetRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRows'
type Page_GetRows_Call struct {
	*mock.Call
}

// GetRows is a helper method to define mock.On call
func (_e *Page_Expecter) GetRows() *Page_GetRows_Call { _ = "STUB: not implemented"; return nil }

func (_c *Page_GetRows_Call) Run(run func()) *Page_GetRows_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_GetRows_Call) Return(_a0 []core.Row) *Page_GetRows_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_GetRows_Call) RunAndReturn(run func() []core.Row) *Page_GetRows_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStructure provides a mock function with no fields
func (_m *Page) GetStructure() *node.Node[core.Structure] { _ = "STUB: not implemented"; return nil }

// Page_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type Page_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *Page_Expecter) GetStructure() *Page_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_GetStructure_Call) Run(run func()) *Page_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_GetStructure_Call) Return(_a0 *node.Node[core.Structure]) *Page_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_GetStructure_Call) RunAndReturn(run func() *node.Node[core.Structure]) *Page_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

// Render provides a mock function with given fields: provider, cell
func (_m *Page) Render(provider core.Provider, cell entity.Cell) { _ = "STUB: not implemented"; return }

// Page_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Page_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - provider core.Provider
//   - cell entity.Cell
func (_e *Page_Expecter) Render(provider interface{}, cell interface{}) *Page_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_Render_Call) Run(run func(provider core.Provider, cell entity.Cell)) *Page_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_Render_Call) Return() *Page_Render_Call { _ = "STUB: not implemented"; return nil }

func (_c *Page_Render_Call) RunAndReturn(run func(core.Provider, entity.Cell)) *Page_Render_Call {
	_ = "STUB: not implemented"
	return nil

	// SetConfig provides a mock function with given fields: config
}

func (_m *Page) SetConfig(config *entity.Config) {
	_ = "STUB: not implemented"

	// Page_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
	return
}

type Page_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - config *entity.Config
func (_e *Page_Expecter) SetConfig(config interface{}) *Page_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_SetConfig_Call) Run(run func(config *entity.Config)) *Page_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_SetConfig_Call) Return() *Page_SetConfig_Call { _ = "STUB: not implemented"; return nil }

func (_c *Page_SetConfig_Call) RunAndReturn(run func(*entity.Config)) *Page_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil

	// SetNumber provides a mock function with given fields: number, total
}

func (_m *Page) SetNumber(number int, total int) { _ = "STUB: not implemented"; return }

// Page_SetNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNumber'
type Page_SetNumber_Call struct {
	*mock.Call
}

// SetNumber is a helper method to define mock.On call
//   - number int
//   - total int
func (_e *Page_Expecter) SetNumber(number interface{}, total interface{}) *Page_SetNumber_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_SetNumber_Call) Run(run func(number int, total int)) *Page_SetNumber_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Page_SetNumber_Call) Return() *Page_SetNumber_Call { _ = "STUB: not implemented"; return nil }

func (_c *Page_SetNumber_Call) RunAndReturn(run func(int, int)) *Page_SetNumber_Call {
	_ = "STUB: not implemented"
	return nil

	// NewPage creates a new instance of Page. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
	// The first argument is typically a *testing.T value.
}

func NewPage(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Page {
	_ = "STUB: not implemented"
	return nil
}
