// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"
	fontrepository "github.com/johnfercher/maroto/v2/pkg/fontrepository"

	fontstyle "github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter { _ = "STUB: not implemented"; return nil }

// AddUTF8Font provides a mock function with given fields: family, style, file
func (_m *Repository) AddUTF8Font(family string, style fontstyle.Type, file string) fontrepository.Repository {
	_ = "STUB: not implemented"
	return *new(fontrepository.Repository)
}

// Repository_AddUTF8Font_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUTF8Font'
type Repository_AddUTF8Font_Call struct {
	*mock.Call
}

// AddUTF8Font is a helper method to define mock.On call
//   - family string
//   - style fontstyle.Type
//   - file string
func (_e *Repository_Expecter) AddUTF8Font(family interface{}, style interface{}, file interface{}) *Repository_AddUTF8Font_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Repository_AddUTF8Font_Call) Run(run func(family string, style fontstyle.Type, file string)) *Repository_AddUTF8Font_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Repository_AddUTF8Font_Call) Return(_a0 fontrepository.Repository) *Repository_AddUTF8Font_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Repository_AddUTF8Font_Call) RunAndReturn(run func(string, fontstyle.Type, string) fontrepository.Repository) *Repository_AddUTF8Font_Call {
	_ = "STUB: not implemented"
	return nil
}

// AddUTF8FontFromBytes provides a mock function with given fields: family, style, bytes
func (_m *Repository) AddUTF8FontFromBytes(family string, style fontstyle.Type, bytes []byte) fontrepository.Repository {
	_ = "STUB: not implemented"
	return *new(fontrepository.Repository)
}

// Repository_AddUTF8FontFromBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUTF8FontFromBytes'
type Repository_AddUTF8FontFromBytes_Call struct {
	*mock.Call
}

// AddUTF8FontFromBytes is a helper method to define mock.On call
//   - family string
//   - style fontstyle.Type
//   - bytes []byte
func (_e *Repository_Expecter) AddUTF8FontFromBytes(family interface{}, style interface{}, bytes interface{}) *Repository_AddUTF8FontFromBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Repository_AddUTF8FontFromBytes_Call) Run(run func(family string, style fontstyle.Type, bytes []byte)) *Repository_AddUTF8FontFromBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Repository_AddUTF8FontFromBytes_Call) Return(_a0 fontrepository.Repository) *Repository_AddUTF8FontFromBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Repository_AddUTF8FontFromBytes_Call) RunAndReturn(run func(string, fontstyle.Type, []byte) fontrepository.Repository) *Repository_AddUTF8FontFromBytes_Call {
	_ = "STUB: not implemented"
	return nil
}

// Load provides a mock function with no fields
func (_m *Repository) Load() ([]entity.CustomFont, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Repository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Repository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *Repository_Expecter) Load() *Repository_Load_Call { _ = "STUB: not implemented"; return nil }

func (_c *Repository_Load_Call) Run(run func()) *Repository_Load_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Repository_Load_Call) Return(_a0 []entity.CustomFont, _a1 error) *Repository_Load_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Repository_Load_Call) RunAndReturn(run func() ([]entity.CustomFont, error)) *Repository_Load_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Repository {
	_ = "STUB: not implemented"
	return nil
}
