// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	core "github.com/johnfercher/maroto/v2/pkg/core"
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"

	mock "github.com/stretchr/testify/mock"

	node "github.com/johnfercher/go-tree/node"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// Row is an autogenerated mock type for the Row type
type Row struct {
	mock.Mock
}

type Row_Expecter struct {
	mock *mock.Mock
}

func (_m *Row) EXPECT() *Row_Expecter { _ = "STUB: not implemented"; return nil }

// Add provides a mock function with given fields: cols
func (_m *Row) Add(cols ...core.Col) core.Row { _ = "STUB: not implemented"; return *new(core.Row) }

// Row_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Row_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - cols ...core.Col
func (_e *Row_Expecter) Add(cols ...interface{}) *Row_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_Add_Call) Run(run func(cols ...core.Col)) *Row_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_Add_Call) Return(_a0 core.Row) *Row_Add_Call { _ = "STUB: not implemented"; return nil }

func (_c *Row_Add_Call) RunAndReturn(run func(...core.Col) core.Row) *Row_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetColumns provides a mock function with no fields
func (_m *Row) GetColumns() []core.Col { _ = "STUB: not implemented"; return nil }

// Row_GetColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetColumns'
type Row_GetColumns_Call struct {
	*mock.Call
}

// GetColumns is a helper method to define mock.On call
func (_e *Row_Expecter) GetColumns() *Row_GetColumns_Call { _ = "STUB: not implemented"; return nil }

func (_c *Row_GetColumns_Call) Run(run func()) *Row_GetColumns_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_GetColumns_Call) Return(_a0 []core.Col) *Row_GetColumns_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_GetColumns_Call) RunAndReturn(run func() []core.Col) *Row_GetColumns_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetHeight provides a mock function with given fields: provider, cell
func (_m *Row) GetHeight(provider core.Provider, cell *entity.Cell) float64 {
	_ = "STUB: not implemented"
	return 0
}

// Row_GetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeight'
type Row_GetHeight_Call struct {
	*mock.Call
}

// GetHeight is a helper method to define mock.On call
//   - provider core.Provider
//   - cell *entity.Cell
func (_e *Row_Expecter) GetHeight(provider interface{}, cell interface{}) *Row_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_GetHeight_Call) Run(run func(provider core.Provider, cell *entity.Cell)) *Row_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_GetHeight_Call) Return(_a0 float64) *Row_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_GetHeight_Call) RunAndReturn(run func(core.Provider, *entity.Cell) float64) *Row_GetHeight_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStructure provides a mock function with no fields
func (_m *Row) GetStructure() *node.Node[core.Structure] { _ = "STUB: not implemented"; return nil }

// Row_GetStructure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructure'
type Row_GetStructure_Call struct {
	*mock.Call
}

// GetStructure is a helper method to define mock.On call
func (_e *Row_Expecter) GetStructure() *Row_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_GetStructure_Call) Run(run func()) *Row_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_GetStructure_Call) Return(_a0 *node.Node[core.Structure]) *Row_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_GetStructure_Call) RunAndReturn(run func() *node.Node[core.Structure]) *Row_GetStructure_Call {
	_ = "STUB: not implemented"
	return nil
}

// Render provides a mock function with given fields: provider, cell
func (_m *Row) Render(provider core.Provider, cell entity.Cell) { _ = "STUB: not implemented"; return }

// Row_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Row_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - provider core.Provider
//   - cell entity.Cell
func (_e *Row_Expecter) Render(provider interface{}, cell interface{}) *Row_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_Render_Call) Run(run func(provider core.Provider, cell entity.Cell)) *Row_Render_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_Render_Call) Return() *Row_Render_Call { _ = "STUB: not implemented"; return nil }

func (_c *Row_Render_Call) RunAndReturn(run func(core.Provider, entity.Cell)) *Row_Render_Call {
	_ = "STUB: not implemented"
	return nil

	// SetConfig provides a mock function with given fields: config
}

func (_m *Row) SetConfig(config *entity.Config) {
	_ = "STUB: not implemented"

	// Row_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
	return
}

type Row_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - config *entity.Config
func (_e *Row_Expecter) SetConfig(config interface{}) *Row_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_SetConfig_Call) Run(run func(config *entity.Config)) *Row_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_SetConfig_Call) Return() *Row_SetConfig_Call { _ = "STUB: not implemented"; return nil }

func (_c *Row_SetConfig_Call) RunAndReturn(run func(*entity.Config)) *Row_SetConfig_Call {
	_ = "STUB: not implemented"
	return nil

	// WithStyle provides a mock function with given fields: style
}

func (_m *Row) WithStyle(style *props.Cell) core.Row {
	_ = "STUB: not implemented"
	return *new(core.Row)
}

// Row_WithStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithStyle'
type Row_WithStyle_Call struct {
	*mock.Call
}

// WithStyle is a helper method to define mock.On call
//   - style *props.Cell
func (_e *Row_Expecter) WithStyle(style interface{}) *Row_WithStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_WithStyle_Call) Run(run func(style *props.Cell)) *Row_WithStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_WithStyle_Call) Return(_a0 core.Row) *Row_WithStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Row_WithStyle_Call) RunAndReturn(run func(*props.Cell) core.Row) *Row_WithStyle_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewRow creates a new instance of Row. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRow(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Row {
	_ = "STUB: not implemented"
	return nil
}
