// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/johnfercher/maroto/v2/pkg/core/entity"
	mock "github.com/stretchr/testify/mock"

	props "github.com/johnfercher/maroto/v2/pkg/props"
)

// Text is an autogenerated mock type for the Text type
type Text struct {
	mock.Mock
}

type Text_Expecter struct {
	mock *mock.Mock
}

func (_m *Text) EXPECT() *Text_Expecter { _ = "STUB: not implemented"; return nil }

// Add provides a mock function with given fields: text, cell, textProp
func (_m *Text) Add(text string, cell *entity.Cell, textProp *props.Text) {
	_ = "STUB: not implemented"
	return
}

// Text_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Text_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - text string
//   - cell *entity.Cell
//   - textProp *props.Text
func (_e *Text_Expecter) Add(text interface{}, cell interface{}, textProp interface{}) *Text_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Text_Add_Call) Run(run func(text string, cell *entity.Cell, textProp *props.Text)) *Text_Add_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Text_Add_Call) Return() *Text_Add_Call { _ = "STUB: not implemented"; return nil }

func (_c *Text_Add_Call) RunAndReturn(run func(string, *entity.Cell, *props.Text)) *Text_Add_Call {
	_ = "STUB: not implemented"
	return nil

	// GetLinesQuantity provides a mock function with given fields: text, textProp, colWidth
}

func (_m *Text) GetLinesQuantity(text string, textProp *props.Text, colWidth float64) int {
	_ = "STUB: not implemented"
	return 0
}

// Text_GetLinesQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinesQuantity'
type Text_GetLinesQuantity_Call struct {
	*mock.Call
}

// GetLinesQuantity is a helper method to define mock.On call
//   - text string
//   - textProp *props.Text
//   - colWidth float64
func (_e *Text_Expecter) GetLinesQuantity(text interface{}, textProp interface{}, colWidth interface{}) *Text_GetLinesQuantity_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Text_GetLinesQuantity_Call) Run(run func(text string, textProp *props.Text, colWidth float64)) *Text_GetLinesQuantity_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Text_GetLinesQuantity_Call) Return(_a0 int) *Text_GetLinesQuantity_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Text_GetLinesQuantity_Call) RunAndReturn(run func(string, *props.Text, float64) int) *Text_GetLinesQuantity_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewText creates a new instance of Text. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewText(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Text {
	_ = "STUB: not implemented"
	return nil
}
